-- 20260924083636_y was generated by `prisma migrate dev`, which does not know about the
-- hand-written vector index and so emitted a DROP for "DocumentChunk_embedding_ivfflat_cos_idx".
-- Since then every retrieval has been an exact sequential scan.
--
-- The index is restored as HNSW rather than ivfflat. ivfflat with lists = 100 built on a small
-- table and the default probes = 1 searches a single list and only then applies the
-- userId/documentId filter, so it can return fewer than K rows even when matches exist.
-- HNSW needs no training data, and the search query enables hnsw.iterative_scan so the filter
-- can never starve the result set. That setting needs pgvector >= 0.8.0, checked here so a too-old
-- extension fails loudly at migration time instead of on the first /ask.
ALTER EXTENSION vector UPDATE;

DO $$
DECLARE
  installed text;
BEGIN
  SELECT extversion INTO installed FROM pg_extension WHERE extname = 'vector';
  IF installed IS NULL OR string_to_array(installed, '.')::int[] < ARRAY[0, 8, 0] THEN
    RAISE EXCEPTION 'pgvector >= 0.8.0 is required for hnsw.iterative_scan (installed: %)', installed;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS "DocumentChunk_embedding_hnsw_cos_idx"
ON "DocumentChunk"
USING hnsw ("embedding" vector_cosine_ops);
