services:
  vector-db:
    image: pgvector/pgvector:pg16
    container_name: backend_vector_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    ports:
      - "5433:5432"
    volumes:
      - vector_postgres_data:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_api
    restart: unless-stopped
    depends_on:
      - vector-db
      - ollama
    env_file:
      - .env
    ports:
      - "4000:4000"
    command: sh -c "pnpm run prisma:generate && pnpm run start"

volumes:
  vector_postgres_data:
  ollama_data:
